### PR TITLE
Bert NER (Name Entity Recognition)

### PR DESCRIPTION
**Pull request by muh005**
Add preliminary Bert Name Entity Recognition.

### CODE REVIEW

**Comment by muh005** [comment]
https://huggingface.co/dslim/bert-base-NER

**Comment by nicklin37** [comment]
In the future, could you keep the comments from review-notebook-app? It generates diffs for the ipynb and lets us review changes much easier. Thanks!

**Review by nicklin37 — COMMENTED** [review]
The additions in this PR are the BERT NER code blocks correct? It doesn't use the KG data if I'm reading it correctly?

**Comment by muh005** [comment]
> In the future, could you keep the comments from review-notebook-app? It generates diffs for the ipynb and lets us review changes much easier. Thanks!

Oops, sorry, I thought it was some dependency bot.

**Comment by muh005** [comment]
> The additions in this PR are the BERT NER code blocks correct? It doesn't use the KG data if I'm reading it correctly?

Yes, I don't have much progress this week. Mainly make the library work.

**Comment by nicklin37** [comment]
> > The additions in this PR are the BERT NER code blocks correct? It doesn't use the KG data if I'm reading it correctly?
> 
> Yes, I don't have much progress this week. Mainly make the library work.

No worries - the results look really good so I'm glad to see progress here.

**Comment by nicklin37** [comment]
> > In the future, could you keep the comments from review-notebook-app? It generates diffs for the ipynb and lets us review changes much easier. Thanks!
> 
> Oops, sorry, I thought it was some dependency bot.

No problem :)

**Review by nicklin37 — APPROVED** [review]
LGTM.

**Pull request merged**
